version: '3.9'

services:
  web:
    # build:
    #   context: .
    #   dockerfile: dockerfiles/web.Dockerfile
    image: driftwood64/a2billing-docker-web
    ports:
     - 80:80
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: web
    depends_on:
      - db
      - sip-server
  sip-server:
    # image: andrius/asterisk:alpine-3.3-13.17.2
    image: driftwood64/a2billing-docker-sip-server
    # build:
    #   context: .
    #   dockerfile: dockerfiles/asterisk.Dockerfile
    ports:
     - 5060:5060
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: sip-server
  db:
    # build:
      # context: .
      # dockerfile: dockerfiles/mysql.Dockerfile
    image: driftwood64/a2billing-docker-db
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
   container_name: phpmyadmin
   image: phpmyadmin/phpmyadmin
   ports:
     - 8080:80
   restart: "unless-stopped"
   env_file:
     - ./.env

volumes:
  mysql_data:
