version: '3.9'

services:
  web:
    image: driftwood64/a2billing-docker-web
    ports:
     - 80:80
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: web
    depends_on:
      - db
      - sip-server
  sip-server:
    image: driftwood64/a2billing-docker-sip-server
    ports:
     - 5060:5060
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: sip-server
  db:
    image: driftwood64/a2billing-docker-db
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
   container_name: phpmyadmin
   image: phpmyadmin/phpmyadmin
   ports:
     - 8080:80
   restart: "unless-stopped"
   env_file:
     - ./.env

volumes:
  mysql_data:
