apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sipserver
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: cluster
    http: 
      paths:
        - path: /sip-server
          pathType: Prefix
          backend:
            service:
              name: sipserver
              port:
                # the TargetPort in Service
                number: 5060

