apiVersion: apps/v1
kind: Deployment
metadata:
  name: sipserver
  namespace: {{ .Values.namespace }}
  labels:
    app: sipserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sipserver
  template:
    metadata:
      labels:
        name: sipserver
    spec:
      containers:
        - name: sipserver
          image: driftwood64/a2billing-docker-sip-server:ubuntu_14_04
          imagePullPolicy: Always
          ports:
            - containerPort: 5060
              protocol: TCP
          envFrom:
          - configMapRef:
              name: a2billing-web-configmap

---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: sipserver
  namespace: {{ .Values.namespace }}
  labels:
    app: sipserver
spec:
  type: ClusterIP
  ports:
    # Equivalent to 5060:80 in docker-compose
    - name: tcp-port
      port: 5060 #port that the service exposes
      targetPort: 5060 #port that the app is receiving requests from via the pod
      protocol: TCP
  selector:
    name: sipserver
# END SERVICE
